### ISSUE TITLE
New config to edit the leaderboard colors

### ISSUE THREAD

**Issue by MrBlasyMSK** [Vecnavium/VecnaLeaderboards#31]
![image](https://user-images.githubusercontent.com/85447029/129906442-624dc5b4-ca2a-4f78-b1f5-3af7cb7e607d.png)
```yml
floating_text_title: "§6- §fTop 10 factions with the most power §6-"
# TAGS: {number} {faction} {power} {members} {bank}
# Sort by power.
floating_text_line: "§6#{number} §f- §6{faction} §fwith §6{power} §fpower(s) and §6{bank} §fmoney"
```
![image](https://user-images.githubusercontent.com/85447029/129906818-d357cb8d-bad8-488c-9b06-4a809e9d2bce.png)

That leaderboard for example is from SimpleFaction and you can edit all the colors and if you want to put something in front or behind to your liking
